### ISSUE TITLE
PHP 5.3 Error

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/pixfields#3]
Un client cu PHP 5.2.17 la activarea pluginului primeste urmatoarea eroare:

" Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/www/vismo.dk/mies/wp-content/plugins/pixfields/pixfields.php on line 77"

**Comment by andreilupu** [comment]
am reparat aici: 645a7f05da9a5ac6b80c4d68f706e786702f51ae
